data:
  embeddings_path: "data/sampled_patient_embedding_biogpt.h5"
  censoring_variability: 30  # Range of variability to add in days to the censoring time

model:
  embedding_dim: 1024
  num_documents: 5
  save_path: "trained_model.pth"

training:
  batch_size: 128
  val_split: 0.2
  num_epochs: 80
  early_stopping_patience: 8
  learning_rate: 0.0001
  use_gpu: true
  gpu_id: 0
  output_dir: "output"

evaluation:
  metric: "c_index"